import { createReadStream } from 'node:fs';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { Readable } from 'node:stream';
import { DeleteObjectCommand, GetObjectCommand, PutObjectCommand, S3Client } from '@aws-sdk/client-s3';
import type { StorageConfig } from '../../config/schema';

/**
 * Where uploaded files live (api-contract §8: outside PostgreSQL, which keeps
 * metadata only). An adapter behind the Integration Gateway pattern (§15):
 * local disk in development, S3-compatible (AWS S3, MinIO) elsewhere.
 * Keys are generated by the server, never taken from a filename.
 */
export interface DocumentStorage {
  /** Stores a new object. Never overwrites: a key is used once. */
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  /** The object's bytes, as a stream. */
  get(key: string): Promise<Readable>;
  /** Removes an object (used to undo an upload whose database write failed). */
  remove(key: string): Promise<void>;
}

/** Keys look like `documents/2026/10/<uuid>`: nothing a client can steer. */
const KEY = /^[a-z0-9]+(?:\/[a-z0-9-]+)+$/;

function assertKey(key: string): void {
  if (!KEY.test(key)) throw new Error(`Invalid storage key '${key}'`);
}

/** Files under a directory, outside any web root; the API streams them after checking a signed URL. */
export class LocalDiskStorage implements DocumentStorage {
  private readonly root: string;

  constructor(root: string) {
    this.root = path.resolve(root);
  }

  private pathOf(key: string): string {
    assertKey(key);
    const file = path.resolve(this.root, key);
    if (!file.startsWith(this.root + path.sep)) throw new Error(`Storage key '${key}' leaves the storage root`);
    return file;
  }

  async put(key: string, body: Buffer): Promise<void> {
    const file = this.pathOf(key);
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, body, { flag: 'wx', mode: 0o600 });
  }

  async get(key: string): Promise<Readable> {
    const file = this.pathOf(key);
    const stream = createReadStream(file);
    // Surface a missing file here rather than as a broken response later.
    await new Promise<void>((resolve, reject) => {
      stream.once('open', () => resolve());
      stream.once('error', reject);
    });
    return stream;
  }

  async remove(key: string): Promise<void> {
    await rm(this.pathOf(key), { force: true });
  }
}

/** An S3 bucket (AWS, or MinIO with `endpoint`); path-style addressing so MinIO works without DNS. */
export class S3Storage implements DocumentStorage {
  private readonly client: S3Client;

  constructor(private readonly config: Extract<StorageConfig, { driver: 's3' }>) {
    this.client = new S3Client({
      region: config.region,
      endpoint: config.endpoint,
      forcePathStyle: config.endpoint !== undefined,
      credentials: { accessKeyId: config.accessKeyId, secretAccessKey: config.secretAccessKey },
    });
  }

  async put(key: string, body: Buffer, contentType: string): Promise<void> {
    assertKey(key);
    await this.client.send(
      new PutObjectCommand({ Bucket: this.config.bucket, Key: key, Body: body, ContentType: contentType, IfNoneMatch: '*' }),
    );
  }

  async get(key: string): Promise<Readable> {
    assertKey(key);
    const res = await this.client.send(new GetObjectCommand({ Bucket: this.config.bucket, Key: key }));
    return res.Body as Readable;
  }

  async remove(key: string): Promise<void> {
    assertKey(key);
    await this.client.send(new DeleteObjectCommand({ Bucket: this.config.bucket, Key: key }));
  }
}

export function createDocumentStorage(config: StorageConfig): DocumentStorage {
  return config.driver === 's3' ? new S3Storage(config) : new LocalDiskStorage(config.localDir);
}
